### ISSUE TITLE
Getting ntest:0 during Testing Pretrained Models

### ISSUE THREAD

**Issue by Qunut999** [yanconglin/Deep-Hough-Transform-Line-Priors#17]
Hi yancoglin,

I attempted to evaluate the pretrained model using "./process.py config/wireframe.yaml <path-to-checkpoint.pth>". However, the terminal shows ntest:0. Could you please advise me on how to resolve this issue?

Thank you for your valuable assistance with this project!

![Screenshot from 2024-07-09 17-24-27](https://github.com/yanconglin/Deep-Hough-Transform-Line-Priors/assets/145352196/1560728b-2e32-42fe-994b-a43908ba5011)

**Comment by yanconglin** [comment]
Looking at the screenshot, I would assume there is a mistake in loading the data, Probably the dataset path is wrong I think, since the number of test samples is 0.

**Comment by yanconglin** [comment]
Hopefully, the problem has been resolved. 
Feel free to reopen.

**Comment by Qunut999** [comment]
Hi @yanconglin,

I apologize for my late response. Thank you for your suggestion regarding the dataset path. I checked it and it appears to be correct, however, I am still facing the issue with ntest:0. It seems there may be another issue preventing the data from loading properly.

Could you please suggest any other potential causes or diagnostic steps I could take to resolve this issue?

Thank you again for your patience and assistance!

**Comment by yanconglin** [comment]
The error indicates that the dataloader could not find and list all data samples. I would suggest debug [this line](https://github.com/yanconglin/Deep-Hough-Transform-Line-Priors/blob/d269559bd4d13a080013c02f9dffcc9b8d090089/ht-lcnn/lcnn/datasets.py#L20).
